
// ClcConstants.java - generated by the SLK parser generator 

public class ClcConstants {

public static final short  NUMBER_ = 257;
public static final short  END_OF_SLK_INPUT_ = 258;


public static final short  NT_EXPRESSION_ = 2049;
public static final short  NT_ADDITIVE_EXPRESSION_ = 2050;
public static final short  NT_ADD_OP_ = 2051;
public static final short  NT_MULTIPLICITIVE_EXPRESSION_ = 2052;
public static final short  NT_MUL_OP_ = 2053;
public static final short  NT_EXPONENTIAL_EXPRESSION_ = 2054;
public static final short  NT_PRIMARY_EXPRESSION_ = 2055;
public static final short  NT_ADD_OP_MULTIPLICITIVE_EXPRESSION_STAR_ = 2056;
public static final short  NT_MUL_OP_EXPONENTIAL_EXPRESSION_STAR_ = 2057;
public static final short  NT_CARET_EXPONENTIAL_EXPRESSION_OPT_ = 2058;


};
