
CFLAGS = -Wall -ggdb -ansi

# libexif  -- biblioteka do wydobywania dodatkowych informacji z plików obrazu
# Description :
# Most digital cameras produce EXIF files, which are JPEG files with
# extra tags that contain information about the image. The EXIF library
# allows you to parse an EXIF file and read the data from those tags.

LDFLAGS = -lexif

clean: 
	rm -f *~ \#* *.o a.out read_exif_data
