
// ClcConstants.cs - generated by the SLK parser generator 

class ClcConstants {

public const short  NUMBER_ = 257;
public const short  END_OF_SLK_INPUT_ = 258;


public const short  NT_EXPRESSION_ = 2049;
public const short  NT_ADDITIVE_EXPRESSION_ = 2050;
public const short  NT_ADD_OP_ = 2051;
public const short  NT_MULTIPLICITIVE_EXPRESSION_ = 2052;
public const short  NT_MUL_OP_ = 2053;
public const short  NT_EXPONENTIAL_EXPRESSION_ = 2054;
public const short  NT_PRIMARY_EXPRESSION_ = 2055;
public const short  NT_ADD_OP_MULTIPLICITIVE_EXPRESSION_STAR_ = 2056;
public const short  NT_MUL_OP_EXPONENTIAL_EXPRESSION_STAR_ = 2057;
public const short  NT_CARET_EXPONENTIAL_EXPRESSION_OPT_ = 2058;


};
