# przykłady z:
#   http://www.math.harvard.edu/computing/c/index.html

julia1:
	cc -lm -o julia1 julia1.c
julia2:
	cc -lm -o julia2 julia2.c
julia:
	cc -lm -o julia julia3.c

# requires gifmerge
#movie:
#	./zoom.sh

# ./julia1 > julia1.ppm


clean:
	rm -f *~ \#*~ *.ppm julia julia1 julia2 julia3
