
// SlkString.h - generated by the SLK parser generator 

#ifndef _SlkSTRING_H
#define _SlkSTRING_H

#ifdef __cplusplus
extern "C" {
#endif

char *SlkGetSymbolName ( short symbol );
char *SlkGetProductionName ( short  production_number );

#ifdef __cplusplus
}
#endif

#endif
