
// SlkTable.h - generated by the SLK parser generator 

#ifndef _SlkTABLE_H
#define _SlkTABLE_H

#ifdef __cplusplus
extern "C" {
#endif

void    Finish ( void );
void    Push ( void );
void    Add ( void );
void    Multiply ( void );
void    Exponent ( void );
void    Negate ( void );

extern void (*SlkActions []) ( void );

#ifdef __cplusplus
}
#endif

#endif
