
#CFLAGS = -Wall -ggdb -ansi -std=c99
CFLAGS = -Wall -ggdb 

multi-0 : multi-0.c

multi-1 : multi-1.c

multi-2 : multi-2.c

multi-3 : multi-3.c

multi-4 : multi-4.c

multi-5 : multi-5.c

dyn_array1 : dyn_array1.c


clean :
	rm -f *~ \#* *.o multi-{0,1,2,3,4,5} dyn_array1
