
// SlkParse.h - generated by the SLK parser generator 

#ifndef _SlkPARSE_H
#define _SlkPARSE_H

#include "SlkLog.h"
#include "SlkToken.h"
#include "SlkError.h"
#include "SlkAction.h"
 
enum _Slk_token_defines { 
  NUMBER_ = 257 
, END_OF_SLK_INPUT_ = 258 
}; 

enum _Slk_Nonterminal_defines { 
  NT_EXPRESSION_ = 2049 
, NT_ADDITIVE_EXPRESSION_ = 2050 
, NT_ADD_OP_ = 2051 
, NT_MULTIPLICITIVE_EXPRESSION_ = 2052 
, NT_MUL_OP_ = 2053 
, NT_EXPONENTIAL_EXPRESSION_ = 2054 
, NT_PRIMARY_EXPRESSION_ = 2055 
, NT_ADD_OP_MULTIPLICITIVE_EXPRESSION_STAR_ = 2056 
, NT_MUL_OP_EXPONENTIAL_EXPRESSION_STAR_ = 2057 
, NT_CARET_EXPONENTIAL_EXPRESSION_OPT_ = 2058 
}; 

short SlkGetTerminalIndex ( short   token );

void SlkParse ( int         display,
                SlkAction  &action, 
                SlkToken   &tokens, 
                SlkError   &error, 
                SlkLog     &log, 
                short       start_symbol ) ;


#endif
