
// SlkString.h - generated by the SLK parser generator 

#ifndef _SlkSTRING_H
#define _SlkSTRING_H

char *SlkGetSymbolName ( short symbol );
char *SlkGetProductionName ( short  production_number );


#endif
