
// SlkTable.h - generated by the SLK parser generator 

#ifndef _SlkTABLE_H
#define _SlkTABLE_H

public:

void    Finish ( void );
void    Push ( void );
void    Add ( void );
void    Multiply ( void );
void    Exponent ( void );
void    Negate ( void );

void    ( SlkAction::*Action [ 7 ] ) ( void );

void    initialize_table ( void );
void
execute ( int  number )   { ( this->*Action [ number ] ) (); }

#endif
